apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-app2
  namespace: new-app2
  labels:
    app: new-app2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: new-app2
  template:
    metadata:
      labels:
        app: new-app2
    spec:
      containers:
      - name: new-app2
        image: ghcr.io/org/new-app2:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
