
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app_id: enterprise
  name: enterprise-33bc347e
  namespace: discovery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enterprise-33bc347e
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: enterprise-33bc347e
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: enterprise-33bc347e
        image: ghostdsbdocker/enterprise:0.1.10_dev-staging
        name: enterprise
        ports:
        - containerPort: 3245
          name: enterprise-port
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
      imagePullSecrets:
      - name: ghostdsb-auth-discovery
      nodeSelector:
        kubernetes.io/arch: amd64
      serviceAccountName: default
