apiVersion: v1
kind: Service
metadata:
  name: t3-5b2f7740
  namespace: discovery
spec:
  ports:
  - port: 80
    targetPort: 4000
    protocol: TCP
    name: t3-service-port
  selector:
    app: t3-5b2f7740
